// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'construction': string;
  'work': string;
}
export const cssExports: CssExports;
export default cssExports;
