// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fadeIn': string;
  'fadeOut': string;
  'finalFade': string;
  'floatUp': string;
  'home': string;
  'light': string;
  'x1': string;
  'x2': string;
  'x3': string;
  'x4': string;
  'x5': string;
  'x6': string;
  'x7': string;
  'x8': string;
  'x9': string;
}
export const cssExports: CssExports;
export default cssExports;
